Repository EternalCodeTeam/EternalCore, pull requests merged in 2022-12, with the labels that each got.

#272 GH-272 Remove useless aliases (Resolve #262)
  eternalcore/src/main/java/com/eternalcode/core/chat/ChatManagerCommand.java
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/EnchantCommand.java
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/SkullCommand.java
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/inventory/AnvilCommand.java
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/inventory/DisposalCommand.java
  eternalcore/src/main/java/com/eternalcode/core/teleport/request/TpaDenyCommand.java
Labels: Architecture

#270 GH-270 Exclude NONE from NoticeType argument tabulation (Resolve #249)
  CHANGELOGS.md
  eternalcore/src/main/java/com/eternalcode/core/command/argument/NoticeTypeArgument.java
Labels: bug, for the sake of humanity

#269 GH-269 Fix problem with possibility of creating warp with the same name (Resolve #255)
  CHANGELOGS.md
  eternalcore/src/main/java/com/eternalcode/core/configuration/lang/ENMessagesConfiguration.java
  eternalcore/src/main/java/com/eternalcode/core/configuration/lang/PLMessagesConfiguration.java
  eternalcore/src/main/java/com/eternalcode/core/language/Messages.java
  eternalcore/src/main/java/com/eternalcode/core/warp/WarpCommand.java
  eternalcore/src/main/java/com/eternalcode/core/warp/WarpManager.java
Labels: bug

#267 GH-267 Fix typo in /tppos (Resolve #254)
  eternalcore/src/main/java/com/eternalcode/core/teleport/command/TeleportToPositionCommand.java
Labels: bug

#225 GH-225 Add more unit tests and fix bugs found by unit tests
  eternalcore/build.gradle.kts
  eternalcore/src/main/java/com/eternalcode/core/EternalCore.java
  eternalcore/src/main/java/com/eternalcode/core/chat/notification/Notification.java
  eternalcore/src/main/java/com/eternalcode/core/user/PrepareUserController.java
  eternalcore/src/test/java/com/eternalcode/core/configuration/composer/DurationComposerTest.java
  eternalcore/src/test/java/com/eternalcode/core/configuration/composer/PositionComposerTest.java
  eternalcore/src/test/java/com/eternalcode/core/configuration/language/LanguageComposerTest.java
  eternalcore/src/test/java/com/eternalcode/core/configuration/language/LocaleComposerTest.java
  eternalcore/src/test/java/com/eternalcode/core/user/PrepareUserControllerTest.java
  eternalcore/src/test/java/com/eternalcode/core/user/UserManagerTest.java
  eternalcore/src/test/java/com/eternalcode/core/util/DurationUtilTest.java
  eternalcore/src/test/java/com/eternalcode/core/util/RandomUtilTest.java
  settings.gradle.kts
Labels: enhancement

#246 GH-246 Add home limit per permission and fix problems with home system
  CHANGELOGS.md
  eternalcore/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
  eternalcore/src/main/java/com/eternalcode/core/configuration/lang/ENMessagesConfiguration.java
  eternalcore/src/main/java/com/eternalcode/core/configuration/lang/PLMessagesConfiguration.java
  eternalcore/src/main/java/com/eternalcode/core/home/HomeManager.java
  eternalcore/src/main/java/com/eternalcode/core/home/command/HomeArgument.java
  eternalcore/src/main/java/com/eternalcode/core/home/command/SetHomeCommand.java
  eternalcore/src/main/java/com/eternalcode/core/language/LanguageInventory.java
  eternalcore/src/main/java/com/eternalcode/core/language/Messages.java
Labels: enhancement

#243 GH-243 Improve comments in config file (Resolve #239, #240)
  eternalcore/src/main/java/com/eternalcode/core/configuration/implementation/LocationsConfiguration.java
  eternalcore/src/main/java/com/eternalcode/core/configuration/implementation/PlaceholdersConfiguration.java
  eternalcore/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
  eternalcore/src/main/java/com/eternalcode/core/configuration/language/LanguageConfiguration.java
Labels: enhancement

#263 GH-263 Add target check to open inventory command (Resolve #256)
  CHANGELOGS.md
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/inventory/InventoryClearCommand.java
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/inventory/InventoryOpenCommand.java
  eternalcore/src/main/java/com/eternalcode/core/configuration/lang/ENMessagesConfiguration.java
  eternalcore/src/main/java/com/eternalcode/core/configuration/lang/PLMessagesConfiguration.java
  eternalcore/src/main/java/com/eternalcode/core/language/Messages.java
Labels: bug, help wanted, for the sake of humanity

#266 GH-266 Add @Name annotations to necessary commands (Resolve #260)
  CHANGELOGS.md
  eternalcore/src/main/java/com/eternalcode/core/chat/feature/adminchat/AdminChatCommand.java
  eternalcore/src/main/java/com/eternalcode/core/chat/feature/privatechat/PrivateChatCommand.java
  eternalcore/src/main/java/com/eternalcode/core/chat/feature/privatechat/PrivateChatReplyCommand.java
  eternalcore/src/main/java/com/eternalcode/core/chat/feature/reportchat/HelpOpCommand.java
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/EnchantCommand.java
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/SpeedCommand.java
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/item/ItemFlagCommand.java
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/item/ItemLoreCommand.java
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/item/ItemNameCommand.java
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/time/TimeCommand.java
  eternalcore/src/main/java/com/eternalcode/core/teleport/command/TeleportToPositionCommand.java
Labels: bug, for the sake of humanity
