Repository EternalCodeTeam/EternalCore, pull requests merged in 2023-09, with the labels that each got.

#497 GH-481 Add feature to support center-aligned text
  eternalcore-core/build.gradle.kts
  eternalcore-core/src/main/java/com/eternalcode/core/EternalCore.java
  eternalcore-core/src/main/java/com/eternalcode/core/adventure/legacy/Legacy.java
  eternalcore-core/src/main/java/com/eternalcode/core/adventure/legacy/LegacyColorProcessor.java
  eternalcore-core/src/main/java/com/eternalcode/core/adventure/resolver/CenterTagResolver.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/container/DisposalCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/container/InventoryOpenCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/ItemLoreCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/ItemNameCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/listener/player/PlayerLoginListener.java
  eternalcore-core/src/main/java/com/eternalcode/core/listener/sign/SignChangeListener.java
Labels: 🆕 feature

#532 GH-532 Update renovate to separate major minor
  renovate.json
Labels: 🌍 for the sake of humanity

#531 GH-531 Update gradle.yml to trigger on pull requests
  .github/workflows/gradle.yml
Labels: 🌍 for the sake of humanity

#534 GH-534 Fix invalid cooldown in delay between messages sent through helpop feature
  eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/reportchat/HelpOpCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/reportchat/HelpOpSettings.java
Labels: 🐛 bug

#536 GH-536 Fix hat command item duplication bug.
  eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/item/HatCommand.java
Labels: 🐛 bug
