Repository EternalCodeTeam/EternalCore, pull requests merged in 2023-05, with the labels that each got.

#434 GH-434 Add teleport to spawn on death & additional check
  eternalcore-core/src/main/java/com/eternalcode/core/EternalCore.java
  eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/spawn/SpawnRespawnController.java
  eternalcore-core/src/main/java/com/eternalcode/core/listener/player/PlayerDeathListener.java
Labels: PR: reviewed-approved, status: accepted

#437 GH-437 Fix home deletion
  eternalcore-core/src/main/java/com/eternalcode/core/database/wrapper/HomeRepositoryOrmLite.java
Labels: PR: partially-approved

#442 GH-430 Separate player speed setting
  eternalcore-core/src/main/java/com/eternalcode/core/EternalCore.java
  eternalcore-core/src/main/java/com/eternalcode/core/command/argument/SpeedTypeArgument.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/SpeedCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/speed/SpeedCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/speed/SpeedType.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/Translation.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Labels: for the sake of humanity
