Repository EternalCodeTeam/EternalCore, pull requests merged in 2023-01, with the labels that each got.

#253 GH-253 Add necessary checks to ignore/unignore feature (Resolve #252, #251)
  CHANGELOGS.md
  eternalcore/src/main/java/com/eternalcode/core/chat/feature/ignore/IgnoreCommand.java
  eternalcore/src/main/java/com/eternalcode/core/chat/feature/ignore/UnIgnoreCommand.java
  eternalcore/src/main/java/com/eternalcode/core/chat/feature/privatechat/PrivateChatCommand.java
  eternalcore/src/main/java/com/eternalcode/core/configuration/lang/ENMessagesConfiguration.java
  eternalcore/src/main/java/com/eternalcode/core/configuration/lang/PLMessagesConfiguration.java
  eternalcore/src/main/java/com/eternalcode/core/language/Messages.java
Labels: bug, for the sake of humanity

#268 GH-268 Improve WorldArgument and weather and time commands (Resolve #264)
  CHANGELOGS.md
  eternalcore/src/main/java/com/eternalcode/core/EternalCore.java
  eternalcore/src/main/java/com/eternalcode/core/command/argument/WorldArgument.java
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/time/DayCommand.java
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/time/NightCommand.java
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/time/TimeCommand.java
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/weather/RainCommand.java
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/weather/SunCommand.java
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/weather/ThunderCommand.java
  eternalcore/src/main/java/com/eternalcode/core/configuration/lang/ENMessagesConfiguration.java
  eternalcore/src/main/java/com/eternalcode/core/configuration/lang/PLMessagesConfiguration.java
  eternalcore/src/main/java/com/eternalcode/core/language/Messages.java
  eternalcore/src/main/java/com/eternalcode/core/teleport/command/TeleportCommand.java
Labels: enhancement

#292 GH-261 Add speed argument for correct tabulation (Resolve #261)
  eternalcore/src/main/java/com/eternalcode/core/EternalCore.java
  eternalcore/src/main/java/com/eternalcode/core/command/argument/SpeedArgument.java
  eternalcore/src/main/java/com/eternalcode/core/command/implementation/SpeedCommand.java
Labels: for the sake of humanity

#293 GH-250 Add option to ignore and unignore all. (Resolve #250)
  eternalcore/src/main/java/com/eternalcode/core/chat/feature/ignore/IgnoreCommand.java
  eternalcore/src/main/java/com/eternalcode/core/chat/feature/ignore/IgnoreRepository.java
  eternalcore/src/main/java/com/eternalcode/core/chat/feature/ignore/UnIgnoreCommand.java
  eternalcore/src/main/java/com/eternalcode/core/database/NoneRepository.java
  eternalcore/src/main/java/com/eternalcode/core/database/wrapper/IgnoreRepositoryOrmLite.java
  eternalcore/src/main/java/com/eternalcode/core/translation/Translation.java
  eternalcore/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
  eternalcore/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Labels: for the sake of humanity

#320 GH-320 Sort gradle plugins alphabetically, readme touchup
  README.md
  core/build.gradle.kts
Labels: documentation, enhancement

#326 GH-324 Add visibility private for config manager (Resolve #324)
  core/src/main/java/com/eternalcode/core/configuration/ConfigurationManager.java
Labels: bug

#325 GH-325 Beautify README.md
  README.md
  assets/readme-banner.png
  core/build.gradle.kts
  core/src/main/java/com/eternalcode/core/bridge/BridgeManager.java
  core/src/main/java/com/eternalcode/core/command/argument/DurationArgument.java
  core/src/main/java/com/eternalcode/core/delay/Delay.java
  core/src/main/java/com/eternalcode/core/util/DurationUtil.java
  core/src/test/java/com/eternalcode/core/user/UserManagerTest.java
  core/src/test/java/com/eternalcode/core/util/RandomUtilTest.java
Labels: documentation
