Repository EternalCodeTeam/EternalCore, pull requests merged in 2023-02, with the labels that each got.

#339 GH-339 Bump LiteCommands to 2.8.3
  core/build.gradle.kts
  core/src/main/java/com/eternalcode/core/feature/adminchat/AdminChatCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/item/EnchantCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/item/GiveCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/item/ItemFlagCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/item/ItemLoreCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/item/ItemNameCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/time/TimeCommand.java
  core/src/main/java/com/eternalcode/core/feature/home/command/SetHomeCommand.java
  core/src/main/java/com/eternalcode/core/feature/privatechat/PrivateChatCommands.java
  core/src/main/java/com/eternalcode/core/feature/reportchat/HelpOpCommand.java
  core/src/main/java/com/eternalcode/core/feature/warp/WarpCommand.java
  core/src/main/java/com/eternalcode/core/teleport/command/TeleportToPositionCommand.java
Labels: PR: reviewed-approved

#346 GH-345 Add permission for bypass teleport waiting (Resolve #345)
  core/src/main/java/com/eternalcode/core/feature/warp/WarpCommand.java
Labels: PR: partially-approved

#344 GH-344 Fix typo in polish translations
  core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Labels: PR: partially-approved

#349 GH-349 Add option to send messages asynchronously. Fix ConcurrentModificationException in TeleportTask.
  core/src/main/java/com/eternalcode/core/EternalCore.java
  core/src/main/java/com/eternalcode/core/feature/afk/AfkMessagesController.java
  core/src/main/java/com/eternalcode/core/notification/Notice.java
  core/src/main/java/com/eternalcode/core/notification/NoticeService.java
  core/src/main/java/com/eternalcode/core/teleport/TeleportTask.java
  core/src/main/java/com/eternalcode/core/teleport/TeleportTaskService.java
Labels: PR: partially-approved

#340 GH-340 Remove or_sender argument
  buildSrc/src/main/kotlin/eternalcode.java-conventions.gradle.kts
  core/build.gradle.kts
  core/src/main/java/com/eternalcode/core/EternalCore.java
  core/src/main/java/com/eternalcode/core/command/argument/PlayerArgOrSender.java
  core/src/main/java/com/eternalcode/core/feature/essentials/FeedCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/FlyCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/GodCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/HealCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/SpeedCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/container/AnvilCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/container/CartographyTableCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/container/EnderchestCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/container/GrindstoneCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/container/InventoryClearCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/container/StonecutterCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/item/GiveCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/playerinfo/PingCommand.java
  core/src/main/java/com/eternalcode/core/teleport/command/TeleportToPositionCommand.java
Labels: PR: partially-approved

#342 GH-265 Add check that spawn is not set yet (Resolve #265)
  core/src/main/java/com/eternalcode/core/configuration/implementation/LocationsConfiguration.java
  core/src/main/java/com/eternalcode/core/feature/spawn/SpawnCommand.java
  core/src/main/java/com/eternalcode/core/shared/Position.java
Labels: PR: partially-approved

#353 GH-353 Add features to README
  README.md
Labels: README, PR: reviewed-approved

#363 GH-363 Add killer to kill command
  core/src/main/java/com/eternalcode/core/listener/player/PlayerDeathListener.java
  core/src/main/java/com/eternalcode/core/translation/Translation.java
  core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
  core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Labels: PR: unreviewed

#360 GH-359 Add reply to target
  core/src/main/java/com/eternalcode/core/EternalCore.java
  core/src/main/java/com/eternalcode/core/command/argument/NoticeTypeArgument.java
  core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
  core/src/main/java/com/eternalcode/core/feature/essentials/FeedCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/FlyCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/HealCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/container/AnvilCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/container/CartographyTableCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/container/DisposalCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/container/EnderchestCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/container/GrindstoneCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/container/InventoryClearCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/container/StonecutterCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/container/WorkbenchCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/gamemode/GameModeCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/item/GiveCommand.java
  core/src/main/java/com/eternalcode/core/notification/Notice.java
  core/src/main/java/com/eternalcode/core/notification/NoticeType.java
  core/src/main/java/com/eternalcode/core/notification/Notification.java
  core/src/main/java/com/eternalcode/core/notification/adventure/AdventureNotificationAnnouncer.java
  core/src/main/java/com/eternalcode/core/translation/Translation.java
  core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
  core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Labels: PR: reviewed-approved
