Repository EternalCodeTeam/EternalCore, pull requests merged in 2023-08, with the labels that each got.

#472 GH-472 Setup readme to get ready for release
  README.md
Labels: 📝 documentation, 🌍 for the sake of humanity, 📄 README

#459 GH-409 Add random teleport command.
  eternalcore-core/src/main/java/com/eternalcode/core/EternalCore.java
  eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/randomteleport/RandomTeleportCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/randomteleport/RandomTeleportService.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/randomteleport/RandomTeleportSettings.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/randomteleport/TeleportResult.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/Translation.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Labels: 🆕 feature, 🌍 for the sake of humanity

#485 GH-484 Add updater
  eternalcore-core/build.gradle.kts
  eternalcore-core/src/main/java/com/eternalcode/core/EternalCore.java
  eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
  eternalcore-core/src/main/java/com/eternalcode/core/updater/UpdaterController.java
  eternalcore-core/src/main/java/com/eternalcode/core/updater/UpdaterService.java
Labels: 🆕 feature

#496 GH-493 Instant teleport to home if one home was set.
  eternalcore-core/src/main/java/com/eternalcode/core/EternalCore.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/home/command/HomeCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/Translation.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Labels: 🆕 feature

#492 GH-489 Reorder home limit check in SetHomeCommand
  eternalcore-core/src/main/java/com/eternalcode/core/feature/home/command/SetHomeCommand.java
Labels: 🐛 bug

#462 GH-462 Add placeholder api
  eternalcore-core/src/main/java/com/eternalcode/core/EternalCore.java
  eternalcore-core/src/main/java/com/eternalcode/core/bridge/BridgeManager.java
  eternalcore-core/src/main/java/com/eternalcode/core/bridge/placeholderapi/PlaceholderApiExtension.java
  eternalcore-core/src/main/java/com/eternalcode/core/bridge/placeholderapi/PlaceholderApiReplacer.java
  eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PlaceholdersConfiguration.java
  eternalcore-core/src/main/java/com/eternalcode/core/placeholder/PlaceholderBukkitRegistryImpl.java
  eternalcore-core/src/main/java/com/eternalcode/core/placeholder/PlaceholderRaw.java
  eternalcore-core/src/main/java/com/eternalcode/core/placeholder/PlaceholderRegistry.java
  eternalcore-core/src/main/java/com/eternalcode/core/placeholder/PlaceholderReplacer.java
  eternalcore-core/src/main/java/com/eternalcode/core/placeholder/PlayerPlaceholderReplacer.java
  eternalcore-core/src/main/java/com/eternalcode/core/placeholder/SimplePlaceholderReplacer.java
  eternalcore-core/src/main/java/com/eternalcode/core/placeholder/SimplePlayerPlaceholderReplacer.java
Labels: 🆕 feature
