Repository EternalCodeTeam/EternalCore, pull requests merged in 2023-04, with the labels that each got.

#387 GH-387 Butcher command implementation
  core/src/main/java/com/eternalcode/core/EternalCore.java
  core/src/main/java/com/eternalcode/core/command/argument/MobEntityArgument.java
  core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
  core/src/main/java/com/eternalcode/core/feature/essentials/mob/ButcherCommand.java
  core/src/main/java/com/eternalcode/core/feature/essentials/mob/MobEntity.java
  core/src/main/java/com/eternalcode/core/feature/essentials/mob/MobFilter.java
  core/src/main/java/com/eternalcode/core/feature/essentials/mob/MobType.java
  core/src/main/java/com/eternalcode/core/translation/Translation.java
  core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
  core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
  core/src/main/java/com/eternalcode/core/util/EntityUtil.java
Labels: PR: reviewed-approved

#391 GH-391 Add WarpInventory system
  core/src/main/java/com/eternalcode/core/EternalCore.java
  core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
  core/src/main/java/com/eternalcode/core/feature/warp/WarpCommand.java
  core/src/main/java/com/eternalcode/core/feature/warp/WarpInventory.java
  core/src/main/java/com/eternalcode/core/feature/warp/config/WarpConfigItem.java
  core/src/main/java/com/eternalcode/core/feature/warp/config/WarpInventoryItem.java
  core/src/main/java/com/eternalcode/core/translation/Translation.java
  core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
  core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
  core/src/main/java/com/eternalcode/core/util/AdventureUtil.java
  core/src/main/java/com/eternalcode/core/util/legacy/Legacy.java
Labels: PR: partially-approved

#393 GH-339 Updated message colorway
  core/src/main/java/com/eternalcode/core/feature/essentials/mob/ButcherCommand.java
  core/src/main/java/com/eternalcode/core/translation/Translation.java
  core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
  core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Labels: PR: unreviewed

#392 GH-392 Add missing item reset
  core/src/main/java/com/eternalcode/core/EternalCore.java
  core/src/main/java/com/eternalcode/core/language/LanguageInventory.java
  core/src/main/java/com/eternalcode/core/language/config/LanguageConfiguration.java
Labels: PR: unreviewed

#398 GH-398 Add option to disable commands
  eternalcore-core/src/main/java/com/eternalcode/core/EternalCore.java
  eternalcore-core/src/main/java/com/eternalcode/core/command/configurator/CommandConfigurator.java
  eternalcore-core/src/main/java/com/eternalcode/core/command/configurator/config/Command.java
  eternalcore-core/src/main/java/com/eternalcode/core/command/configurator/config/CommandConfiguration.java
  eternalcore-core/src/main/java/com/eternalcode/core/command/configurator/config/SubCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/configuration/ConfigurationManager.java
Labels: PR: unreviewed

#403 GH-403 Fix codestyle
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/classpath/URLClassLoaderAccessor.java
Labels: PR: partially-approved

#401 GH-401 Spring cleaning
  README.md
  eternalcore-core/src/main/java/com/eternalcode/core/feature/ignore/IgnoreCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/privatechat/PrivateChatCommands.java
Labels: PR: reviewed-approved

#404 GH-404 Add SuppressWarnings annotation
  eternalcore-paper/src/main/java/com/eternalcode/containers/AdditionalContainerPaper.java
Labels: PR: reviewed-approved

#407 GH-407 Add missing hashtag
  eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Labels: PR: reviewed-approved

#410 GH-410 Add missing permissions for home
  eternalcore-core/src/main/java/com/eternalcode/core/feature/home/command/DelHomeCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/home/command/SetHomeCommand.java
Labels: PR: reviewed-approved

#411 GH-411 Change CI artifact name
  .github/workflows/autoapprove.yml
  .github/workflows/gradle.yml
Labels: type: feature, PR: unreviewed, PR: partially-approved

#416 GH-416 Remove publisher. Fix dependency loader.
  eternalcore-api/src/main/java/com/eternalcode/core/user/UserManager.java
  eternalcore-core/src/main/java/com/eternalcode/core/EternalCore.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkChangeEvent.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkMessagesController.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkService.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/privatechat/PrivateChatPresenter.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/privatechat/PrivateChatService.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/privatechat/PrivateMessage.java
  eternalcore-core/src/main/java/com/eternalcode/core/publish/LocalPublisher.java
  eternalcore-core/src/main/java/com/eternalcode/core/publish/PublishContent.java
  eternalcore-core/src/main/java/com/eternalcode/core/publish/Publisher.java
  eternalcore-core/src/main/java/com/eternalcode/core/publish/Subscribe.java
  eternalcore-core/src/main/java/com/eternalcode/core/publish/Subscriber.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/EternalCoreLoader.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/classloader/IsolatedClassAccessorLoader.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/classloader/IsolatedClassLoader.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/classloader/IsolatedClassLoaderImpl.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/classloader/URLClassLoaderAccessor.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/DependencyLoader.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/DependencyLoaderImpl.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/relocation/RelocationHandler.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/repository/Repository.java
Labels: PR: reviewed-approved

#412 GH-412 Separate spawn command functions
  eternalcore-api/src/main/java/com/eternalcode/core/user/UserManager.java
  eternalcore-api/src/main/java/com/eternalcode/core/viewer/Viewer.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/spawn/SpawnCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/viewer/BukkitViewerImpl.java
Labels: PR: reviewed-approved

#417 GH-417 Add death messages by cause of death
  eternalcore-core/src/main/java/com/eternalcode/core/listener/player/PlayerDeathListener.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/Translation.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
  raw_commands_docs.json
  raw_features_docs.json
Labels: PR: partially-approved

#424 GH-424 Make task shadowJar depends on others.
  .github/workflows/gradle.yml
  eternalcore-plugin/build.gradle.kts
Labels: type: security

#421 GH-421 Improve afk system
  eternalcore-core/src/main/java/com/eternalcode/core/EternalCore.java
  eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkController.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkService.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkSettings.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/afk/AfkTask.java
Labels: PR: reviewed-approved

#431 GH-431 Remove panda utilities from api module.
  eternalcore-api/build.gradle.kts
  eternalcore-api/src/main/java/com/eternalcode/core/user/User.java
  eternalcore-api/src/main/java/com/eternalcode/core/user/UserClientNoneSettings.java
  eternalcore-api/src/main/java/com/eternalcode/core/user/UserClientSettings.java
  eternalcore-api/src/main/java/com/eternalcode/core/user/UserManager.java
  eternalcore-api/src/main/java/com/eternalcode/core/user/UserSettings.java
  eternalcore-api/src/main/java/com/eternalcode/core/user/UserSettingsImpl.java
  eternalcore-core/src/main/java/com/eternalcode/core/command/argument/UserArgument.java
  eternalcore-core/src/main/java/com/eternalcode/core/command/contextual/UserContextual.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/container/DisposalCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/privatechat/PrivateChatService.java
  eternalcore-core/src/main/java/com/eternalcode/core/language/LanguageInventory.java
  eternalcore-core/src/main/java/com/eternalcode/core/listener/player/PlayerLoginListener.java
  eternalcore-core/src/main/java/com/eternalcode/core/notification/Notice.java
  eternalcore-core/src/main/java/com/eternalcode/core/user/PrepareUserController.java
  eternalcore-core/src/main/java/com/eternalcode/core/user/UserClientBukkitSettings.java
  eternalcore-core/src/main/java/com/eternalcode/core/viewer/BukkitViewerProvider.java
  eternalcore-core/src/test/java/com/eternalcode/core/test/OptionAssertions.java
  eternalcore-core/src/test/java/com/eternalcode/core/user/PrepareUserControllerTest.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/classloader/IsolatedClassAccessorLoader.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/repository/Repository.java
Labels: PR: reviewed-approved
