Repository EternalCodeTeam/EternalCore, pull requests merged in 2024-02, with the labels that each got.

#670 GH-670 Butcher command arguments fix
  eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/mob/ButcherArgument.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/mob/ButcherCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/essentials/mob/MobEntityArgument.java
Labels: 🐛 bug

#672 GH-672 HelpOp API implementation
  eternalcore-api/src/main/java/com/eternalcode/core/feature/helpop/event/HelpOpEvent.java
  eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/helpop/HelpOpCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/helpop/HelpOpSettings.java
Labels: 🆕 feature

#671 GH-664 RandomTeleport API implementation
  eternalcore-api-example/build.gradle.kts
  eternalcore-api-example/src/main/java/com/eternalcode/example/EternalCoreApiExamplePlugin.java
  eternalcore-api-example/src/main/java/com/eternalcode/example/feature/randomteleport/ApiRandomTeleportCommand.java
  eternalcore-api-example/src/main/java/com/eternalcode/example/feature/randomteleport/ApiRandomTeleportListener.java
  eternalcore-api/src/main/java/com/eternalcode/core/EternalCoreApi.java
  eternalcore-api/src/main/java/com/eternalcode/core/feature/randomteleport/RandomTeleportService.java
  eternalcore-api/src/main/java/com/eternalcode/core/feature/randomteleport/TeleportResult.java
  eternalcore-api/src/main/java/com/eternalcode/core/feature/randomteleport/event/PreRandomTeleportEvent.java
  eternalcore-api/src/main/java/com/eternalcode/core/feature/randomteleport/event/RandomTeleportEvent.java
  eternalcore-core/src/main/java/com/eternalcode/core/EternalCoreApiImpl.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/randomteleport/RandomTeleportServiceImpl.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/randomteleport/RandomTeleportType.java
Labels: 🆕 feature

#674 GH-658 AdminChat API implementation
  eternalcore-api/src/main/java/com/eternalcode/core/feature/adminchat/event/AdminChatEvent.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/adminchat/AdminChatCommand.java
Labels: 🆕 feature

#685 GH-666 Add Warp System API (WarpEvent and WarpService)
  eternalcore-api/src/main/java/com/eternalcode/core/EternalCoreApi.java
  eternalcore-api/src/main/java/com/eternalcode/core/feature/warp/Warp.java
  eternalcore-api/src/main/java/com/eternalcode/core/feature/warp/WarpService.java
  eternalcore-api/src/main/java/com/eternalcode/core/feature/warp/event/WarpTeleportEvent.java
  eternalcore-core/src/main/java/com/eternalcode/core/EternalCoreApiImpl.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/warp/WarpArgument.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/warp/WarpCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/warp/WarpConfigRepository.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/warp/WarpImpl.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/warp/WarpInventory.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/warp/WarpManager.java
Labels: 🔓 API
