Repository EternalCodeTeam/EternalCore, pull requests merged in 2024-06, with the labels that each got.

#798 GH-792 Fix updating of libraries. (dependency loader)
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/Dependency.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/DependencyCollector.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/DependencyLoadResult.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/DependencyLoaderImpl.java
Labels: ✅ needs testing

#802 GH-799 Improve dependency loader performance with parallel downloading and relocation.
  buildSrc/src/main/kotlin/Versions.kt
  buildSrc/src/main/kotlin/eternalcore-repositories.gradle.kts
  eternalcore-plugin/build.gradle.kts
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/Dependency.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/DependencyCollector.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/DependencyLoadEntry.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/DependencyLoadResult.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/dependency/DependencyLoaderImpl.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/pom/PomXmlScanner.java
  eternalcore-plugin/src/main/java/com/eternalcode/core/loader/relocation/RelocationHandler.java
Labels: 🔄 dependencies

#703 GH-661 Escalate Ignore developer API
  eternalcore-api-example/src/main/java/com/eternalcode/example/EternalCoreApiExamplePlugin.java
  eternalcore-api-example/src/main/java/com/eternalcode/example/feature/ignore/ApiIgnoreCommand.java
  eternalcore-api-example/src/main/java/com/eternalcode/example/feature/ignore/ApiIgnoreListener.java
  eternalcore-api/src/main/java/com/eternalcode/core/EternalCoreApi.java
  eternalcore-api/src/main/java/com/eternalcode/core/feature/ignore/IgnoreService.java
  eternalcore-api/src/main/java/com/eternalcode/core/feature/ignore/event/IgnoreAllEvent.java
  eternalcore-api/src/main/java/com/eternalcode/core/feature/ignore/event/IgnoreEvent.java
  eternalcore-api/src/main/java/com/eternalcode/core/feature/ignore/event/UnIgnoreAllEvent.java
  eternalcore-api/src/main/java/com/eternalcode/core/feature/ignore/event/UnIgnoreEvent.java
  eternalcore-core/src/main/java/com/eternalcode/core/EternalCoreApiImpl.java
  eternalcore-core/src/main/java/com/eternalcode/core/database/wrapper/AbstractRepositoryOrmLite.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/ignore/IgnoreCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/ignore/IgnoreRepository.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/ignore/IgnoreRepositoryOrmLite.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/ignore/IgnoreService.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/ignore/IgnoreServiceImpl.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/ignore/UnIgnoreCommand.java
Labels: 🔓 API
