Repository EternalCodeTeam/EternalCore, pull requests merged in 2025-08, with the labels that each got.

#1076 GH-994 Add lightning command
  eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/catboy/CatBoySettings.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/catboy/CatboyConfig.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/catboy/CatboyController.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/catboy/CatboyServiceImpl.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/catboy/CatboySettings.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/lightning/LightningCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/lightning/LightningConfig.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/lightning/LightningSettings.java
Labels: 🆕 feature, ⚙️ architecture

#1094 GH-991 Add MOTD feature
  eternalcore-core/src/main/java/com/eternalcode/core/feature/joinmessage/PlayerJoinMessageController.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/motd/MotdJoinController.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/motd/messages/ENMotdMessages.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/motd/messages/MotdMessages.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/motd/messages/PLMotdMessages.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/Translation.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Labels: 🆕 feature

#1118 GH-952 Expand repair time and create dedicated section for messages
  eternalcore-core/src/main/java/com/eternalcode/core/configuration/migrations/Migrations.java
  eternalcore-core/src/main/java/com/eternalcode/core/configuration/migrations/Migrations_0008_Move_repair_to_dedicated_section.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/repair/RepairCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/repair/RepairConfig.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/repair/messages/ENRepairMessages.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/repair/messages/PLRepairMessages.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/repair/messages/RepairMessages.java
  eternalcore-core/src/main/java/com/eternalcode/core/litecommand/argument/messages/ArgumentMessages.java
  eternalcore-core/src/main/java/com/eternalcode/core/litecommand/argument/messages/ENArgumentMessages.java
  eternalcore-core/src/main/java/com/eternalcode/core/litecommand/argument/messages/PLArgumentMessages.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/Translation.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Labels: 🆕 good first issue, 🚀 EternalCore 2.0

#1128 GH-993 Add freeze and unfreeze player commands
  eternalcore-core/src/main/java/com/eternalcode/core/feature/freeze/FreezeCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/freeze/UnfreezeCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/freeze/messages/ENFreezeMessages.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/freeze/messages/FreezeMessages.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/freeze/messages/PLFreezeMessages.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/Translation.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/ENTranslation.java
  eternalcore-core/src/main/java/com/eternalcode/core/translation/implementation/PLTranslation.java
Labels: 🆕 feature, 🚀 EternalCore 2.0

#1124 GH-1124 Rename and improve `HomesConfig` properties; update related usage and add migration.
  eternalcore-core/src/main/java/com/eternalcode/core/configuration/migrations/Migration_0009_Improve_Homes_Config.java
  eternalcore-core/src/main/java/com/eternalcode/core/configuration/migrations/Migrations.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/home/HomeTeleportService.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/home/HomesConfig.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/home/HomesSettings.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/home/command/HomeCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/home/command/SetHomeCommand.java
Labels: 🔧 enhancement

#1125 GH-1125 Improve `RandomTeleportConfig` comments for better UX
  eternalcore-core/src/main/java/com/eternalcode/core/configuration/implementation/PluginConfiguration.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/randomteleport/RandomTeleportConfig.java
Labels: 🔧 enhancement

#1140 GH-1040 Add ItemCommand and refactor give command
  eternalcore-core/src/main/java/com/eternalcode/core/feature/give/GiveCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/give/GiveService.java
  eternalcore-core/src/main/java/com/eternalcode/core/feature/item/ItemCommand.java
  eternalcore-core/src/main/java/com/eternalcode/core/litecommand/argument/StackAmountArgument.java
Labels: 🔧 enhancement
